# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('DateCreated', models.DateTimeField(default=datetime.datetime(2016, 6, 20, 6, 30, 9, 380715))),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
