# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_auto_20160620_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('DateCreated', models.DateTimeField(default=datetime.datetime(2016, 6, 20, 6, 32, 22, 176082))),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.AlterField(
            model_name='district',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 6, 32, 22, 175355)),
        ),
        migrations.AddField(
            model_name='campus',
            name='DistrictId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.District'),
        ),
    ]
