# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_auto_20160620_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
